### ISSUE TITLE
Add new dependencies

### ISSUE THREAD

**Issue by adehecq** [adehecq/ragmac_xdem#27]
- rioxarray
- psutil

**Comment by dshean** [comment]
Pretty sure you don't actually need psutil.  Can get cpu count from multiprocessing.  I think my branch had that modification.

**Comment by friedrichknuth** [comment]
PR #29 adds `rioxarray` to the `environment.yml`, which resolves this issue.

I removed the `psutil` dependency, as it isn't necessary.

Note `psutil` lets you easily switch between `psutil.cpu_count(logical=True)` (use virtual cores)  and `psutil.cpu_count(logical=False)` (use only physical cores) , which is convenient on shared resources. I primarily use it for this purpose, but there might be other/better ways that don't require additional dependancies. In any case, with `nproc` in `main_experiment2.py` the user has higher level control and can decide upstream.
