### ISSUE TITLE
Unexpected keyword argument 'dilate_mask'

### ISSUE THREAD

**Issue by friedrichknuth** [adehecq/ragmac_xdem#6]
```
python ./scripts/main_experiment2.py
Case NO_Vestisen not implemented
Case CL_NPI not implemented
Case RU_FJL not implemented

### DEMs selection ###
For date 2000-02-01 found 2 DEMs
For date 2012-10-01 found 9 DEMs
For date 2019-10-01 found 12 DEMs

### Coregister DEMs ###
Postprocessing DEMs:   0%|                                                                                                                                                 | 0/23 [01:54<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/mnt/Backups/knuth/sw/miniconda3/envs/ragmac_xdem/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/Backups/knuth/sw/repos/ragmac_xdem/ragmac_xdem/dem_postprocessing.py", line 317, in _postproc_wrapper
    outputs = postprocessing_single(
  File "/mnt/Backups/knuth/sw/repos/ragmac_xdem/ragmac_xdem/dem_postprocessing.py", line 221, in postprocessing_single
    dem_coreg = coreg.apply(dem, dilate_mask=False)
TypeError: apply() got an unexpected keyword argument 'dilate_mask'
"""
```

**Comment by adehecq** [comment]
This is because the version conda/pip installed is not from the latest commit, but the one with the latest tagged version (0.0.5).
For some reason, even running `pip install "git+https://github.com/GlacioHack/xdem.git@main" -U` does not install the latest xdem.
Although the commit hash printed on screen seem correct, the code is not up-to-date, as can be seen by running `python -c "import xdem; coreg = xdem.coreg.NuthKaab(); help(coreg.apply)"`
The printed documentation should contain a kwargs argument, which was not implemented in the latest tagged version.

**Comment by adehecq** [comment]
This seems to be working!
`pip install "git+https://github.com/GlacioHack/xdem.git@main" -U --no-deps --force-reinstall`

**Comment by adehecq** [comment]
The issue should be solved with commits 7a7b570 and dac429e.
@friedrichknuth, can you please test it and confirm?

**Comment by adehecq** [comment]
The only remaining issue is that if I install with pip using the setup.cfg file, it still does not install the latest version:
```
pip uninstall xdem -y
pip install -e . --no-cache-dir
```
Any idea why?

**Comment by friedrichknuth** [comment]
Confirmed issue is resolve by installing environment with changes from commit 7a7b570 :tada:

The following tests run without issue and produce the expected outputs.
```
python ./scripts/main_experiment2.py
python ./scripts/main_experiment1.py CH_Aletschgletscher
python ./scripts/main_experiment1.py AT_Hintereisferner
```

Regarding installing with pip, I think the syntax in the setup.cfg is [outdated](https://stackoverflow.com/a/32689886/11996067). I couldn't quite get it to work using the setup.cfg, rather had to move the install_requires (from url) arguments to the setup.py file, like so https://github.com/adehecq/ragmac_xdem/compare/friedrichknuth-patch-1.

**Comment by friedrichknuth** [comment]
But installing with without creating the environment with conda first (going straight to `pip install -e .` still seems to cause issues :/

```
...
Successfully built geoutils xdem
Failed to build rasterio numba llvmlite
...
```

My recommendation is to just make the install with conda using the environment.yml mandatory.

**Comment by adehecq** [comment]
Ok, thanks for the tips ! If the current README lines work, then let's not change anything. We can always figure out something better for the final version of the repository.
