### ISSUE TITLE
Issue calculating slope for RU_FJL case

### ISSUE THREAD

**Issue by adehecq** [adehecq/ragmac_xdem#81]
In the RU_FJL case, the reference DEM does not have exactly square pixels, which raises an error when calculating the slope, e.g. when filtering the ddem in the CTL run.
Fails wtih ValueError: 

> ValueError: Quadric surface fit requires the same X and Y resolution ((29.999999999999986, 30.0) was given). This was required by: ['slope']

To reproduce, e.g.: `python scripts/main_experiment2.py -mode DEMdiff_autoselect -c RU_FJL -r CTL`

**Comment by dshean** [comment]
Ah, precision issues.  A `gdal_edit.py` (or similar API) call to set resolution could offer simple workaround.  Seems like there should be some GDAL/rasterio flag to guarantee square pixels in output.

**Comment by adehecq** [comment]
Solved in #82.
